-- STRING FUNCTIONS IN MYSQL:
SELECT LENGTH("HELLO 'WORLD😀") AS LENGTH_COUNT; 

SELECT CHAR_LENGTH("HELLO 'WORLD😀") AS LENGTH_COUNT;

SELECT CONCAT(FIRST_NAME,' ',LAST_NAME) AS FULL_NAME
FROM EMPLOYEES;
use hr;
SELECT CONCAT_WS('-',FIRST_NAME,LAST_NAME) AS FULL_NAME
FROM EMPLOYEES;

SELECT INSTR("DATABASE","BASE"); 
-- syntax instr("string","sub-string")

SELECT LOCATE("BASE","DATABASE");
-- syntax locate("sub-string","string")

-- PADDING FUNCTION:
SELECT LPAD('45', 5, '0') AS left_padded;

SELECT LPAD('45',5,'A');

SELECT RPAD('20',6,'0');

SELECT ASCII('/n'); -- ENTER KEY
SELECT ASCII("A");

SELECT CONCAT('Hi', SPACE(10), 'There');
-- left , right and mid, substring, upper(),ucase(), lower(),lcase()
-- EXTRACT FUNCTION:
SELECT LEFT('MYSQL',2);
SELECT RIGHT('MYSQL',2);
SELECT SUBSTRING("HELLO MYSQL",7,5);
SELECT MID("HELLO MYSQL",7,5);
-- CASE CONVERSION FUNCTION:
SELECT UPPER("mysql");
SELECT UCASE("mysql");
SELECT LOWER("MYSQL");
SELECT LCASE("MYSQL");
-- TRIM FUNCTION - REMOVE SPACES 
SELECT TRIM("    MYSQL  ");
SELECT LTRIM("    MYSQL  ");
SELECT RTRIM("    MYSQL  ");

